### ISSUE TITLE
Is there a web version of this tool?

### ISSUE THREAD

**Issue by kfishster** [zomle/homm3calculator#1]
Hello! I was researching the guard size question while watching some HoTA streams, and saw this project on github. I was wondering whether a web version of this exists and where it might be.

If not, I would love to take on a project and create a web version using some of the insights from this codebase, definitely giving credit to this repo as the genesis :)

Thank you in advance!

**Comment by zomle** [comment]
Hi! When I started to work on this project I couldn't find a web (or any other) version of guard calculation, to be honest I haven't looked for one since. So I don't know if it exists or not.
But regardless, feel free to use any/all part of this project, good luck (and thanks for the credit)!

Once it's open for public, I can put a link in this project's readme file if you want, just let me know.

Also be aware, that the random map generator sometimes generates specific resource piles (wood/ore(1400 AI value) or gem/crystal/sulfur/mercury (2000 AI value)) and sometimes generates "random resource" objects (1500 AI value), that would end up as a specific resource pile. Meaning that during calculations both a wood and a gem pile could worth 1500 AI value.
